import '@/styles/colors.css';
import '@/styles/globals.css';
import '@/styles/tiptap.css';
import '@/styles/typography.css';

import { GeistSans } from 'geist/font/sans';
import { type Metadata } from 'next';

import { TooltipProvider } from '@/lib/shadcn/ui/tooltip';
import { TRPCReactProvider } from '@/lib/trpc/react';
import { ClerkProvider } from '@clerk/nextjs';
import { ThemeProvider } from '../modules/theme/providers/theme-provider';

export const metadata: Metadata = {
	title: 'Create T3 App',
	description: 'Generated by create-t3-app',
	icons: [{ rel: 'icon', url: '/favicon.ico' }]
};

export default function RootLayout({
	children
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en" className={GeistSans.variable}>
			<body className="overflow-hidden bg-background" suppressHydrationWarning>
				<ClerkProvider>
					<TRPCReactProvider>
						<ThemeProvider>
							<TooltipProvider>{children}</TooltipProvider>
						</ThemeProvider>
					</TRPCReactProvider>
				</ClerkProvider>
			</body>
		</html>
	);
}
